name: Telegram File Upload Test

on:
  workflow_dispatch:

jobs:
  telegram_file_test:
    runs-on: ubuntu-latest

    steps:
      - name: Create dummy zip
        run: |
          mkdir test_output
          echo "Halo dari GitHub Actions 🚀" > test_output/readme.txt
          zip -r test_build.zip test_output/

      - name: Send dummy zip to Telegram
        run: |
          ZIP_PATH="test_build.zip"
          curl -F chat_id=${{ secrets.TG_CHAT_ID }} \
               -F document=@"$ZIP_PATH" \
               -F caption="📦 *Test upload file berhasil!*\n\
               File contoh: \`$ZIP_PATH\`\n\
               Repository: ${{ github.repository }}" \
               -F parse_mode="Markdown" \
               https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendDocument
